tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import tugas2_profile.urls as profile
import tugas2_riwayat.urls as riwayat
import tugas2_search.urls as search
from tugas2_status.custom_auth import auth_login, auth_logout
import tugas2_status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url = '/status/', permanent = False), name='index'),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^riwayat/', include(riwayat,namespace='riwayat')),
    url(r'^search/', include(search,namespace='search')),
    url(r'^status/', include(status,namespace='status')),
    url(r'^login/auth_login', auth_login, name='auth_login'),
    url(r'^login/auth_logout', auth_logout, name='auth_logout'),
]

templates/partials/footer.html
<div class="footer">
    <h1 style="text-align:center">
        <small><em> Made with love by Kelompok Tujuh &copy; </em></small>
    </h1>
</div>

templates/partials/header.html
<!-- Your Header Here -->
<!-- templates/lab_5/partials/header.html -->
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <a class="navbar-brand" href="{% url 'status:index' %}">Home</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav nav-right pull-right">
<!---->
      </ul>
    </div>
</nav>