tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import tugas2_profile.urls as profile
import tugas2_riwayat.urls as riwayat
import tugas2_search.urls as search
from tugas2_status.custom_auth import auth_login, auth_logout
import tugas2_status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url = '/status/', permanent = False), name='index'),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^riwayat/', include(riwayat,namespace='riwayat')),
    url(r'^search/', include(search,namespace='search')),
    url(r'^status/', include(status,namespace='status')),
    url(r'^login/auth_login', auth_login, name='auth_login'),
    url(r'^login/auth_logout', auth_logout, name='auth_logout'),
]

tugas2_status/urls.py
from django.conf.urls import url
from .views import index, login, dashboard, add_status
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^login/$', login, name='login'),
	url(r'^add_status', add_status, name='add_status'),
    url(r'^(?P<npm>.*)/$', dashboard, name='dashboard'),
    
]

tugas2_status/models.py
from django.db import models

# Create your models here.

tugas2_status/forms.py
from django import forms

class Status_Form(forms.Form):
    error_messages = {
        'required': 'Status tidak boleh kosong.',
        'invalid': 'Status terlalu panjang.'
    }
    text_attrs = {
        'type': 'text',
        'cols': 40,
        'rows': 3,
        'class': 'status-text',
        'placeholder':'Update status anda'
    }

    text = forms.CharField(label='', required=True, max_length=100, widget=forms.TextInput(attrs=text_attrs), error_messages=error_messages)

tugas2_status/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from tugas2_profile.models import Mahasiswa, Status
from .forms import Status_Form

response = {}

def index(request):
    if 'user_login' in request.session:
        response['login'] = True
        return HttpResponseRedirect(reverse('status:dashboard', args=(request.session['kode_identitas'],)))
    else:
        response['login'] = False
        html = 'home.html'
        return render(request, html, response)

def login(request):
    html = 'login.html'
    return render(request, html, response)

def dashboard(request, npm):
    if not 'user_login' in request.session.keys():
        return HttpResponseRedirect(reverse('status:login'))
    elif Mahasiswa.objects.filter(kode_identitas=npm).exists():
        response['can_submit'] = False
        if (npm == request.session['kode_identitas']):
            response['can_submit'] = True
        mahasiswa = Mahasiswa.objects.get(kode_identitas=npm)
        status = Status.objects.filter(mahasiswa=mahasiswa)

        response['status'] = status
        response['status_form'] = Status_Form
        set_data_for_session(request, npm)
        html = 'status/status.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect(reverse('status:dashboard', args=(request.session['kode_identitas'],)))

def set_data_for_session(request, npm):
    response['kode_identitas'] = request.session['kode_identitas']

    mahasiswa = Mahasiswa.objects.get(kode_identitas=npm)
    response['nama'] = mahasiswa.nama

    status = Status.objects.filter(mahasiswa=mahasiswa)
    response['count_status'] =  status.count()
    response['last_status'] = status.last()
    response['kode_identitas_visit'] = npm
    response['app_id'] = 1

def add_status(request):
    #print("add_status")
    form = Status_Form(request.POST or None)
    if (request.method == 'POST' and form.is_valid()):
        text = request.POST['text']
        mahasiswa = Mahasiswa.objects.get(kode_identitas=request.session['kode_identitas'])

        status = Status(mahasiswa=mahasiswa, text=request.POST['text'])
        status.save()
    return HttpResponseRedirect(reverse('status:dashboard', args=(request.session['kode_identitas'],)))

tugas2_status/templates/status/status.html
{% extends "dashboard.html" %}

{% block table %}
{% if can_submit %}
<style type="text/css">
    #input-list {
    margin-bottom: 30px;
}
.page-head {
    margin-top: 10px;
    margin-bottom: 10px;
}
.list-head {
    margin-bottom: 20px;
}
.status-text {
    margin: : 50px;
    display: block;
    width: 100%;
    height: 50px;
    margin-top: 10px;
    margin-bottom: 5px;
}
#submit {
    width: 90px;
}
.flex-item {
    word-wrap: break-word;
    margin-top: 10px;
    margin-bottom: 10px;
}
.author-profile {
    display: flex;
    flex-direction: row;
    flex-wrap: wrap;
    justify-content: flex-start;
    align-items: flex-start;
    align-content: flex-start;
    background-color: green;
    border-radius: 3px;
    padding: 10px;
}
.author-profile-data {
    margin-right: 5px;
    flex-grow: 0;
    flex-shrink: 0;
}
.status-list {
    border-width: thick;
}
.status-list-text {
    background-color: rgb(225, 225, 225);
    z-index: 15;
    padding-left: 10px;
    padding-right: 10px;
    padding-top: 5px;
    height: 70px;
    font-size: 20px;
    text-align: justify;
}
.status-list-date-added {
    background-color: rgb(60, 130, 200);
    padding: 6px;
    padding-left: 10px;
    font-weight: bold;
    color: white;
}
</style>
<section name="input-list" id="input-list">
    <div class="container">
        <form id="form" method="POST" action="{% url 'status:add_status' %}">
            {% csrf_token %}
            {{ status_form }}
            <input id="submit" type="submit" class="btn btn-success" value="Post">
            <br>
        </form>
    </div>
</section>
{% endif %}
<section name="my-status" id="my-status">
    <div class="container">
        <div class="flex">
            {% if status %}
                {% for data in status reversed %}
                    <div class="flex-item">
                        <div class="status-list">
                        <div class="status-list-date-added">
                                {{data.created_date}}
                            </div>
                            <div class="status-list-text">
                                {{data.text}}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
</section>
{% endblock %}