tugas2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView
import tugas2_profile.urls as profile
import tugas2_riwayat.urls as riwayat
import tugas2_search.urls as search
from tugas2_status.custom_auth import auth_login, auth_logout
import tugas2_status.urls as status

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url = '/status/', permanent = False), name='index'),
    url(r'^profile/', include(profile,namespace='profile')),
    url(r'^riwayat/', include(riwayat,namespace='riwayat')),
    url(r'^search/', include(search,namespace='search')),
    url(r'^status/', include(status,namespace='status')),
    url(r'^login/auth_login', auth_login, name='auth_login'),
    url(r'^login/auth_logout', auth_logout, name='auth_logout'),
]

tugas2_profile/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^edit/$', to_edit, name='to_edit'),
    url(r'^edits/$', edit_mahasiswa, name='edits'),
    url(r'^keahlian/$', to_keahlian, name='to_keahlian'),
    url(r'^keahlians/$', add_keahlian, name='keahlians'),
    url(r'^(?P<npm>.*)/$', index, name='index'),
]

tugas2_status/urls.py
from django.conf.urls import url
from .views import index, login, dashboard, add_status
from .custom_auth import auth_login, auth_logout

urlpatterns = [
	url(r'^$', index, name='index'),
	url(r'^login/$', login, name='login'),
	url(r'^add_status', add_status, name='add_status'),
    url(r'^(?P<npm>.*)/$', dashboard, name='dashboard'),
    
]

templates/dashboard.html
{% extends "layout/base.html" %}

{% block content %}
<div class="row">

	<div class="panel panel-primary">
	  <div class="panel-heading">
	    <h1>Selamat Datang, {{ nama }}!
			<a href="{% url 'auth_logout' %}" class="btn btn-danger pull-right">Logout</a>
		</h1>
	  </div>
	  <div class="panel-body">
			<img class="img-circle" src	="https://image.freepik.com/free-icon/male-user-profile-picture_318-37825.jpg" width="8%"  alt="foto">
			<br>

			<h4>Jumlah Status : {{count_status}}</h4>
			<h4>Status Terakhir:
				{% if last_status %}
					{{last_status.text}}
				{% else %}
					Tidak ada
			    {% endif %}
            </h4>
		</div>
		<div class="panel-footer">
			<button class="btn btn-primary"> Lihat Forum</button>
			<a href="{% url 'profile:to_edit' %}" class="btn btn-primary"> Edit Profile </a>


	</div>

	</div>
</div>
<div>
    <!-- Nav tabs -->
    <ul class="nav nav-tabs nav-justified" id="tab-feature" role="tablist">
        <li role="presentation" {% if app_id == 1 %} class="active" {% endif %}>
            <a href="{% url 'status:dashboard' kode_identitas_visit %}"> Status </a>
        </li>
        <li role="presentation" {% if app_id == 2 %} class="active" {% endif %}>
            <a href="{% url 'profile:index' kode_identitas_visit %}"> Profile </a>
        </li>
        <li role="presentation" {% if app_id == 3 %} class="active" {% endif %}>
            <a href="{% url 'riwayat:index' kode_identitas_visit %}"> Riwayat </a>
        </li>
        <li role="presentation" {% if app_id == 4 %} class="active" {% endif %}>
            <a href="{% url 'search:index' kode_identitas_visit %}"> Search </a>
        </li>
    </ul>
</div>
<script>

</script>
{% block table %}

{% endblock %}
{% endblock %}

templates/home.html
{% extends "layout/base.html" %}
{% block content %}
<div class="row">
	<img class="img-circle" src="http://2.bp.blogspot.com/_3wYzXkja15c/S8SoDvip-VI/AAAAAAAAACI/YM0dL1rkqcI/S1600-R/Kesimpulan+Lapen+Laporan+Penelitian+Nasionalisasi+Perusahaan+Swasta+Oleh+Pemerintah+di+Amerika+Serikat.jpg" width="8%"  alt="foto"/>
	<h3> Perusahaan dummy </h3>
	<br>
	<img class="img-circle" src="https://www.hipwee.com/wp-content/uploads/2014/11/bill-gates-jpg-850x571.jpg" width="8%" height="100px"  alt="foto" style="margin-left: 15%; margin-right: 2%; display: inline-block">
	<h3 style="display: inline-block"> Orang dummy 1</h3>
	<br>
	<br>
	<img class="img-circle" src="https://4.bp.blogspot.com/-0jyKPMwE8Sw/Vt58pCElM-I/AAAAAAAAH0Q/uDHpgJx3vp8/s1600/cara-berpikir-orang-kaya-yang-berbeda-dengan-anda.jpg" width="8%"  alt="foto" style="margin-left: 15%; margin-right: 2%; display: inline-block">
	<h3 style="display: inline-block"> Orang dummy 2</h3>
	<br>
	<br>
	<img class="img-circle" src="https://cdn.brilio.net/news/2016/12/05/109243/750xauto-nama-panjang-orang-ini-bikin-kamu-keseleo-lidah-tirukan-kalau-bisa-161205g.jpg" width="8%" height="100px" alt="foto" style="margin-left: 15%; margin-right: 2%; display: inline-block">
	<h3 style="display: inline-block"> Orang dummy 3</h3>
	<br>
	<a href="{% url 'status:dashboard' kode_identitas %}" class="btn btn-primary" style="margin-left: 25%">Login Mahasiswa</a>
</div>

{% endblock %}

templates/login.html
{% extends "layout/base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="rata-tengah">
            <div class="judul">
                <h1> Halaman Login </h1>
                <p class="text-info"> Gunakan <b> akun SSO </b> untuk login </p>
            </div>
            <form action="{% url 'auth_login' %}" method="POST">
                {% csrf_token %}
                <p>
                    <label for="username"> Your username </label>
                    <input type="text" id="username" name="username" required>
                </p>
                <p>
                    <label for="password"> Your password </label>
                    <input type="password" id="password" name="password" required>
                </p>
                <input type="submit" class="btn btn-primary">
            </form>
        </div>
    </div>
</div>
{% endblock %}